version: '3.9'

services:
  lint-tests:
    build:
      context: credit-line
      dockerfile: Dockerfile
      target: dev
    image: huma-underwriter-simple-creditline-ci:latest
    command: ["make", "lint-check"]
    environment:
      - ENV=test

  tests:
    build:
      context: credit-line
      dockerfile: Dockerfile
      target: dev
    image: huma-underwriter-simple-creditline-ci:latest
    command: ["make", "test"]
    environment:
      - ENV=test
      - WEB3_PROVIDER_URL
      - ETHERSCAN_API_KEY
      - ETHERSCAN_BASE_URL
      - INSTRUMENTATION_ENABLED=false
      - DATADOG_API_KEY=""
